# ================================================================
# Values to change:
# ================================================================
# SUBDOMAINS (mario would be the value for mario.duckdns.org)
# TOKEN 
# /home/user/duckdns directory
# ================================================================
# Difficulty: Easy

version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=something
      - TOKEN=get-your-token-from-duckdns.org
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - /home/user/duckdns:/config #optional
    restart: unless-stopped
