# ================================================================
# Values to change:
# ================================================================
# /media/user/storage:/home/user/ directory
# /home/user/ftpd:/etc/pure-ftpd/passwd directory
# FTP_USER_NAME: username 
# FTP_USER_PASS: password
# FTP_USER_HOME: /home/user (should be same as user in directory)
# ================================================================
# Difficulty: Easy
# ================================================================
# Notes: Only connect with ACTIVE connection and insecure FTP

version: '3'
services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/media/user/storage:/home/user/"
      - "/home/user/ftpd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: password
      FTP_USER_HOME: /home/user
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
