# ================================================================
# Values to change:
# ================================================================
# BASIC_AUTH_USERNAME
# BASIC_AUTH_PASSWORD
# /home/user/swag/log/nginx:/opt/log (directory where nginx logs are stored)
# ================================================================
# Difficulty: Easy
version: '2'  
services:
  goaccess:
    image: 'xavierh/goaccess-for-nginxproxymanager:develop'
    container_name: goaccess
    restart: unless-stopped
    ports:
      - '7880:7880'
    environment:
      - TZ=Australia/Melbourne
      - SKIP_ARCHIVED_LOGS=False #optional
      - DEBUG=False #optional
      - BASIC_AUTH=True #optional
      - BASIC_AUTH_USERNAME=user #optional
      - BASIC_AUTH_PASSWORD=password #optional\
      - LOG_TYPE=NGINX_ACCESS
    volumes:
      - "/home/user/swag/log/nginx:/opt/log"
