version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /home/user/postgres/data:/var/lib/postgresql/data
      - /home/user/postgres/logs:/var/log/postgresql
      - /home/user/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - /home/user/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf",]
volumes:
  data:
    driver: local
  logs:
    driver: local
