# ================================================================
# Values to change:
# ================================================================
# URL=username.duckdns.org (needed for HTTPS)
# /home/user/swag:/config
# ================================================================
# Difficulty: Easy
# ================================================================
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - URL=username.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - EMAIL=username@gmail.com #optional
      - ONLY_SUBDOMAINS=false
    volumes:
      -  /home/user/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
